### ISSUE TITLE
Space in names break viualisation

### ISSUE THREAD

**Issue by grasshoffm** [CostaLab/scrna_seurat_pipeline#11]
I ran the pipeline on a data set and the sample names and stages had spaces. 

In the output html, the link to the xlsx-files are broken, while the files are present.

**Comment by chengmingbo** [comment]
Fixed on version: [a186e78](https://github.com/CostaLab/scrna_seurat_pipeline/commit/a186e7881173e653fcc5dfe8aa71937ad3b809e2)
